spring:
  servlet:
    multipart:
      max-file-size: 50MB  #单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小
server:
  port: 8183
#  context-path: CgFramework
WebConfig:
  AppSettings:
    SiteUserIDSaveKey: cg_SiteUserID
    LogPath: /log
    IsCreateLogSubDir: 1
  ConnectionSettings:
    AppDefault:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.100.31:3306/bison.tt.cagoe.com?serverTimezone=GMT%2b8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL&characterEncoding=UTF-8
      username: bisonttcagoecom
      password: vUAQ2hnxKW0Bt4e!@712
      #   Druid数据源配置
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 50
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnBorrow: false
      #配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnReturn: false
      #打开PsCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
